import asyncio
from typing import AsyncIterator


class DemoAI:
    """Local AI simulator for demos and development."""

    def _project_response(self, prompt: str) -> str:
        return """
{
  "title": "AI Customer Support Platform",
  "summary": "A full-stack SaaS platform that uses AI to automate customer support while allowing human agents to review and manage conversations.",
  "features": [
    "User authentication",
    "Customer management",
    "AI-powered support conversations",
    "Conversation history",
    "Human agent review",
    "Analytics dashboard",
    "Role-based access control"
  ],
  "architecture": {
    "frontend": [
      "Next.js",
      "React",
      "TypeScript"
    ],
    "backend": [
      "FastAPI",
      "Python",
      "GraphQL"
    ],
    "database": [
      "PostgreSQL",
      "Redis"
    ],
    "infrastructure": [
      "Docker",
      "GitHub Actions",
      "Cloud deployment"
    ]
  },
  "api": [
    "POST /auth/login",
    "GET /customers",
    "POST /conversations",
    "GET /conversations/{id}",
    "POST /ai/respond",
    "GET /analytics"
  ],
  "database": [
    "users",
    "customers",
    "conversations",
    "messages",
    "ai_runs",
    "analytics_events"
  ],
  "implementation_plan": [
    "Set up the Next.js frontend",
    "Create the FastAPI backend",
    "Configure PostgreSQL",
    "Implement authentication",
    "Create customer and conversation APIs",
    "Integrate the AI service",
    "Add streaming responses",
    "Build the analytics dashboard",
    "Add automated tests",
    "Configure CI/CD and deployment"
  ]
}
""".strip()

    def _code_generation_response(self, prompt: str) -> str:
        return """
{
  "project_name": "nexora-generated-app",
  "summary": "A full-stack AI customer support SaaS starter generated by Nexora AI.",
  "files": [
    {
      "path": "apps/api/app/main.py",
      "language": "python",
      "content": "from fastapi import FastAPI\\n\\nfrom app.router import router\\n\\napp = FastAPI(\\n    title='AI Customer Support API',\\n    version='1.0.0',\\n)\\n\\napp.include_router(router)\\n\\n\\n@app.get('/health')\\nasync def health():\\n    return {'status': 'ok'}\\n"
    },
    {
      "path": "apps/api/app/models.py",
      "language": "python",
      "content": "from pydantic import BaseModel, EmailStr\\n\\n\\nclass Customer(BaseModel):\\n    name: str\\n    email: EmailStr\\n\\n\\nclass Conversation(BaseModel):\\n    customer_id: int\\n    message: str\\n"
    },
    {
      "path": "apps/api/app/service.py",
      "language": "python",
      "content": "from app.models import Customer\\n\\n\\nclass CustomerService:\\n    async def list_customers(self) -> list[Customer]:\\n        return []\\n\\n    async def create_customer(\\n        self,\\n        customer: Customer,\\n    ) -> Customer:\\n        return customer\\n"
    },
    {
      "path": "apps/api/app/router.py",
      "language": "python",
      "content": "from fastapi import APIRouter\\n\\nfrom app.models import Customer\\nfrom app.service import CustomerService\\n\\nrouter = APIRouter(prefix='/api')\\nservice = CustomerService()\\n\\n\\n@router.get('/customers')\\nasync def list_customers():\\n    return await service.list_customers()\\n\\n\\n@router.post('/customers')\\nasync def create_customer(customer: Customer):\\n    return await service.create_customer(customer)\\n"
    },
    {
  "path": "apps/api/app/config.py",
  "language": "python",
  "content": "from pydantic_settings import BaseSettings\\n\\n\\nclass Settings(BaseSettings):\\n    app_name: str = 'Nexora Generated API'\\n    environment: str = 'development'\\n    database_url: str = 'sqlite:///./app.db'\\n    secret_key: str = 'change-me'\\n\\n\\nsettings = Settings()\\n"
},
{
  "path": "apps/api/app/database.py",
  "language": "python",
  "content": "from sqlalchemy import create_engine\\nfrom sqlalchemy.orm import declarative_base, sessionmaker\\n\\nfrom app.config import settings\\n\\nengine = create_engine(settings.database_url)\\nSessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)\\nBase = declarative_base()\\n\\n\\ndef get_db():\\n    db = SessionLocal()\\n    try:\\n        yield db\\n    finally:\\n        db.close()\\n"
},
{
  "path": "apps/api/app/ai_service.py",
  "language": "python",
  "content": "class AIService:\\n    async def generate_response(\\n        self,\\n        message: str,\\n        conversation_id: int,\\n    ) -> str:\\n        return (\\n            f'AI response generated for conversation '\\n            f'{conversation_id}: {message}'\\n        )\\n"
},
{
  "path": "apps/api/app/analytics.py",
  "language": "python",
  "content": "from fastapi import APIRouter\\n\\nrouter = APIRouter(\\n    prefix='/api/analytics',\\n    tags=['Analytics'],\\n)\\n\\n\\n@router.get('/overview')\\nasync def overview():\\n    return {\\n        'total_customers': 642,\\n        'total_conversations': 12482,\\n        'ai_resolution_rate': 0.87,\\n        'average_response_time': 1.8,\\n    }\\n"
},
{
  "path": "apps/api/tests/test_customers.py",
  "language": "python",
  "content": "from fastapi.testclient import TestClient\\n\\nfrom app.main import app\\n\\nclient = TestClient(app)\\n\\n\\ndef test_list_customers():\\n    response = client.get('/api/customers')\\n\\n    assert response.status_code == 200\\n    assert isinstance(response.json(), list)\\n"
},
{
  "path": "apps/api/tests/test_ai.py",
  "language": "python",
  "content": "from fastapi.testclient import TestClient\\n\\nfrom app.main import app\\n\\nclient = TestClient(app)\\n\\n\\ndef test_ai_response():\\n    response = client.post(\\n        '/api/ai/respond',\\n        params={\\n            'message': 'Hello AI',\\n            'conversation_id': 1,\\n        },\\n    )\\n\\n    assert response.status_code == 200\\n    assert 'response' in response.json()\\n"
},
{
  "path": "apps/api/.env.example",
  "language": "text",
  "content": "DATABASE_URL=sqlite:///./app.db\\nSECRET_KEY=change-me\\nENVIRONMENT=development\\n"
},
{
  "path": "apps/api/README.md",
  "language": "markdown",
  "content": "# Nexora Generated API\\n\\nFastAPI backend generated by Nexora AI.\\n\\n## Features\\n\\n- Customer management\\n- AI responses\\n- Conversation APIs\\n- Analytics\\n- Health monitoring\\n- Automated tests\\n\\n## Run\\n\\n```bash\\nuvicorn app.main:app --reload\\n```\\n"
},
    {
      "path": "apps/api/tests/test_health.py",
      "language": "python",
      "content": "from fastapi.testclient import TestClient\\n\\nfrom app.main import app\\n\\nclient = TestClient(app)\\n\\n\\ndef test_health():\\n    response = client.get('/health')\\n\\n    assert response.status_code == 200\\n    assert response.json() == {'status': 'ok'}\\n"
    },
    {
      "path": "apps/api/requirements.txt",
      "language": "text",
      "content": "fastapi\\nuvicorn[standard]\\npydantic\\npydantic-settings\\nemail-validator\\nsqlalchemy\\npytest\\nhttpx\\n"
    },
    {
      "path": "apps/web/app/page.tsx",
      "language": "typescript",
      "content": "import Dashboard from './components/Dashboard';\\n\\nexport default function Home() {\\n  return (\\n    <main className='min-h-screen bg-black p-10 text-white'>\\n      <div className='mx-auto max-w-6xl'>\\n        <h1 className='mt-3 text-4xl font-semibold'>AI Customer Support</p>\\n        <h1 className='mt-3 text-4xl font-semibold'>\\n          Customer Support Dashboard\\n        </h1>\\n        <h1 className='mt-3 text-4xl font-semibold'>\\n          Manage customers and AI-powered support conversations.\\n        </p>\\n        <div className='mt-10'>\\n          <Dashboard />\\n        </div>\\n      </div>\\n    </main>\\n  );\\n}\\n"
    },
    {
      "path": "apps/web/app/components/Dashboard.tsx",
      "language": "typescript",
      "content": "const customers = [\\n  { name: 'Acme Corporation', status: 'Active' },\\n  { name: 'Northstar Labs', status: 'Active' },\\n  { name: 'Vertex Systems', status: 'Pending' },\\n];\\n\\nexport default function Dashboard() {\\n  return (\\n    <section className='rounded-2xl border border-white/10 bg-white/[0.03] p-6'>\\n      <div className='flex items-center justify-between'>\\n        <div>\\n          <h2 className='text-xl font-semibold'>Customers</h2>\\n          <p className='mt-1 text-sm text-white/40'>\\n            Manage your customer accounts.\\n          </p>\\n        </div>\\n\\n        <span className='rounded-full bg-white/5 px-3 py-1 text-sm text-white/40'>\\n          {customers.length} customers\\n        </span>\\n      </div>\\n\\n      <div className='mt-6 space-y-2'>\\n        {customers.map((customer) => (\\n          <div\\n            key={customer.name}\\n            className='flex items-center justify-between rounded-xl border border-white/5 bg-black/20 p-4'\\n          >\\n            <span className='text-sm text-white/70'>\\n              {customer.name}\\n            </span>\\n\\n            <span className='text-sm text-white/30'>\\n              {customer.status}\\n            </span>\\n          </div>\\n        ))}\\n      </div>\\n    </section>\\n  );\\n}\\n"
    },
    {
      "path": "apps/web/lib/api.ts",
      "language": "typescript",
      "content": "const API_URL =\\n  process.env.NEXT_PUBLIC_API_URL ??\\n  'http://localhost:8000';\\n\\nexport async function getHealth() {\\n  const response = await fetch(`${API_URL}/health`);\\n\\n  if (!response.ok) {\\n    throw new Error('API request failed');\\n  }\\n\\n  return response.json();\\n}\\n\\nexport async function getCustomers() {\\n  const response = await fetch(\\n    `${API_URL}/api/customers`,\\n  );\\n\\n  if (!response.ok) {\\n    throw new Error('Unable to load customers');\\n  }\\n\\n  return response.json();\\n}\\n"
    },
    {
      "path": "apps/web/.env.example",
      "language": "text",
      "content": "NEXT_PUBLIC_API_URL=http://localhost:8000\\n"
    },
    {
      "path": "apps/web/package.json",
      "language": "json",
      "content": "{\\n  \\"name\\": \\"generated-web\\",\\n  \\"private\\": true,\\n  \\"scripts\\": {\\n    \\"dev\\": \\"next dev\\",\\n    \\"build\\": \\"next build\\",\\n    \\"start\\": \\"next start\\"\\n  },\\n  \\"dependencies\\": {\\n    \\"next\\": \\"latest\\",\\n    \\"react\\": \\"latest\\",\\n    \\"react-dom\\": \\"latest\\"\\n  }\\n}\\n"
    },
    {
      "path": "Dockerfile",
      "language": "dockerfile",
      "content": "FROM python:3.12-slim\\n\\nWORKDIR /app\\n\\nCOPY apps/api/requirements.txt ./requirements.txt\\n\\nRUN pip install --no-cache-dir -r requirements.txt\\n\\nCOPY apps/api/app ./app\\n\\nEXPOSE 8000\\n\\nCMD [\\\"uvicorn\\\", \\\"app.main:app\\\", \\\"--host\\\", \\\"0.0.0.0\\\", \\\"--port\\\", \\\"8000\\\"]\\n"
    },
    {
      "path": ".gitignore",
      "language": "text",
      "content": "node_modules\\n.next\\n__pycache__\\n.venv\\n.env\\n*.pyc\\n"
    },
    {
      "path": "README.md",
      "language": "markdown",
      "content": "# Generated Application\\n\\nThis full-stack application was generated by Nexora AI.\\n\\n## Stack\\n\\n- Next.js\\n- React\\n- TypeScript\\n- FastAPI\\n- Python\\n- PostgreSQL\\n- Redis\\n\\n## Backend\\n\\n```bash\\ncd apps/api\\npython -m uvicorn app.main:app --reload\\n```\\n\\n## Frontend\\n\\n```bash\\ncd apps/web\\nnpm install\\nnpm run dev\\n```\\n"
    }
  ]
}
""".strip()

    def _response(self, prompt: str) -> str:
        prompt_lower = prompt.lower()

        # Code generation must be checked before the
        # architecture response because both prompts
        # contain JSON-related instructions.
        if (
            "full-stack starter application" in prompt_lower
            or "complete file content" in prompt_lower
            or "generate a full-stack" in prompt_lower
            or "code generation" in prompt_lower
        ):
            return self._code_generation_response(prompt)

        if (
            "project specification" in prompt_lower
            or "return json with exactly these fields" in prompt_lower
        ):
            return self._project_response(prompt)

        if any(
            word in prompt_lower
            for word in ["fastapi", "backend", "api"]
        ):
            return (
                "FastAPI is a strong choice for an AI backend because it "
                "provides async request handling, automatic API documentation, "
                "and built-in validation through Pydantic.\n\n"
                "For Nexora AI, the backend handles AI requests, streaming "
                "responses, and application logic while keeping the frontend "
                "independent from the AI provider."
            )

        if any(
            word in prompt_lower
            for word in ["next.js", "nextjs", "frontend", "react"]
        ):
            return (
                "Next.js provides the application layer for the Nexora AI "
                "frontend. It handles the user interface while FastAPI manages "
                "AI requests and backend logic.\n\n"
                "This separation allows the frontend and backend to evolve "
                "independently."
            )

        if any(
            word in prompt_lower
            for word in ["investor", "startup", "business"]
        ):
            return (
                "Nexora AI is an AI-native application platform designed with "
                "a modular architecture.\n\n"
                "The platform separates the frontend, API layer, AI service, "
                "and provider integration. This creates a foundation for "
                "authentication, persistent conversations, usage controls, "
                "and multiple AI providers."
            )

        if any(
            word in prompt_lower
            for word in ["hello", "hi", "hey"]
        ):
            return (
                "Hello! I'm Nexora AI. I can help you explore the platform, "
                "architecture, APIs, and AI-powered workflows."
            )

        return (
            f'I understand your request about "{prompt.strip()}".\n\n'
            "Nexora AI is processing this request through its application "
            "layer. In production, this layer can route the request to the "
            "configured AI provider and stream the response back to the client.\n\n"
            "This demo response is generated locally so the complete "
            "frontend-to-backend experience can be demonstrated without "
            "an external API dependency."
        )

    async def generate(
        self,
        prompt: str,
    ) -> tuple[str, dict[str, int]]:
        content = self._response(prompt)

        await asyncio.sleep(0.4)

        prompt_tokens = max(1, len(prompt.split()))
        completion_tokens = max(1, len(content.split()))

        usage = {
            "prompt_tokens": prompt_tokens,
            "completion_tokens": completion_tokens,
            "total_tokens": prompt_tokens + completion_tokens,
        }

        return content, usage

    async def stream(
        self,
        prompt: str,
    ) -> AsyncIterator[str]:
        content = self._response(prompt)
        words = content.split(" ")

        for index, word in enumerate(words):
            chunk = word

            if index < len(words) - 1:
                chunk += " "

            yield chunk

            await asyncio.sleep(0.025)