from fastapi import APIRouter
from fastapi.responses import Response

router = APIRouter(
    prefix="/api/projects",
    tags=["Projects"],
)


def build_architecture_document(project: dict) -> str:
    architecture = project.get("architecture", {})

    frontend = architecture.get("frontend", [])
    backend = architecture.get("backend", [])
    database = architecture.get("database", [])
    infrastructure = architecture.get("infrastructure", [])

    features = project.get("features", [])
    api = project.get("api", [])
    database_entities = project.get("database", [])
    implementation_plan = project.get(
        "implementation_plan",
        [],
    )

    def bullet_list(items: list[str]) -> str:
        if not items:
            return "- None specified"

        return "\n".join(
            f"- {item}"
            for item in items
        )

    return f"""# {project.get("title", "Nexora AI Project")}

## Executive Summary

{project.get("summary", "No project summary provided.")}

---

## Product Capabilities

{bullet_list(features)}

---

## System Architecture

### Frontend

{bullet_list(frontend)}

### Backend

{bullet_list(backend)}

### Data Layer

{bullet_list(database)}

### Infrastructure

{bullet_list(infrastructure)}

---

## API Surface

{bullet_list(api)}

---

## Data Model

{bullet_list(database_entities)}

---

## Implementation Plan

{chr(10).join(
    f"{index + 1}. {step}"
    for index, step in enumerate(implementation_plan)
) if implementation_plan else "No implementation plan provided."}

---

## Generated by Nexora AI

This architecture document was generated by Nexora AI from the original product requirements.
"""


@router.post("/architecture/export")
async def export_architecture(project: dict):
    document = build_architecture_document(project)

    filename = (
        project.get("title", "nexora-project")
        .lower()
        .replace(" ", "-")
        .replace("/", "-")
    )

    return Response(
        content=document,
        media_type="text/markdown",
        headers={
            "Content-Disposition": (
                f'attachment; filename="{filename}-architecture.md"'
            )
        },
    )